saved:
  timestamp: '202101100137'
setup:
  batch_size: 32
  data_path: ''
  federated_runs: 200
  learning_rate: 0.01
  momentum: 0.9
  n_clients: 10
  n_of_federated_runs: 200
  num_of_epochs: 10
  random_clients: 0.5
  save_dir: ../runs
