saved:
  timestamp: '202101100137'
setup:
  batch_size: 32
  data_path: ''
  federated_runs: 1
  learning_rate: 0.01
  momentum: 0.9
  multiprocessing: 0
  n_Rcal: 1
  n_bits: 100
  n_clients: 10
  n_of_federated_runs: 1
  n_train_offset: 1
  network_type: NN
  num_of_epochs: 10
  random_clients: 0.4
  save_dir: ./runs
  save_tests: 1
  tests_dir: ./tests
  to_save: 0
