setup:
  data_path: ""
  n_clients: 10
  learning_rate: 0.01
  num_of_epochs: 10
  batch_size: 32
  momentum: 0.9
  random_clients: 0.5
  n_of_federated_runs: 1
  federated_runs: 1
  save_dir : '../runs'
